export const routePath = {
  home: "/",
  notes: "notes",
  dummy: "dummy",
  pyq: "pyq",
  login: "login",
  signup: "signup",
  adminLogin: "admin-login",
  department: "department",
  users: "users",
  addUser: "add-users",
  viewDepartment: "view-department",
  addDepartment: "add-department",
  editDepartment: "edit-department",
  about: "about",
  modelQuestionGenerator: "model-question-paper",
  gradePredictor: "grade-Calculator",
  attendanceRegulator: "attendance-calculator",
  viewUser: "view-user",
  editUser: "edit-user",
  verifyOTP: "verify-otp",
};
